namespace Catalog.SGas.Entities;
public class SalaryTimeSheetDetail
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid IdSalaryTimeSheet { get; set; }
    public decimal AdvancePaymentAmount { get; set; }
    public decimal AdvancePaymentAmount141 { get; set; }
    public decimal BasicSalaryAmount { get; set; }
    public decimal ColumnMoney1 { get; set; }
    public decimal ColumnMoney10 { get; set; }
    public decimal ColumnMoney2 { get; set; }
    public decimal ColumnMoney3 { get; set; }
    public decimal ColumnMoney4 { get; set; }
    public decimal ColumnMoney5 { get; set; }
    public decimal ColumnMoney6 { get; set; }
    public decimal ColumnMoney7 { get; set; }
    public decimal ColumnMoney8 { get; set; }
    public decimal ColumnMoney9 { get; set; }
    public decimal ColumnNumber1 { get; set; }
    public decimal ColumnNumber10 { get; set; }
    public decimal ColumnNumber2 { get; set; }
    public decimal ColumnNumber3 { get; set; }
    public decimal ColumnNumber4 { get; set; }
    public decimal ColumnNumber5 { get; set; }
    public decimal ColumnNumber6 { get; set; }
    public decimal ColumnNumber7 { get; set; }
    public decimal ColumnNumber8 { get; set; }
    public decimal ColumnNumber9 { get; set; }
    public decimal CompanyHealthInsurranceAmount { get; set; }
    public decimal CompanyLaborUnionContributionAmount { get; set; }
    public decimal CompanySocialInsuranceAmount { get; set; }
    public decimal CompanyUnemploymentInsurranceAmount { get; set; }
    public Guid EmployeeId { get; set; }
    public decimal FinalIncomePitAmount { get; set; }
    public decimal HealthInsurranceAmount { get; set; }
    public decimal IncomeForPitAmount { get; set; }
    public decimal IncomeTaxAmount { get; set; }
    public decimal InsuranceSalaryAmount { get; set; }
    public decimal LaborUnionContributionAmount { get; set; }
    public decimal NetAmount { get; set; }
    public decimal NonPaidWorkingValue { get; set; }
    public decimal NonWorkingDay { get; set; }
    public decimal NonWorkingSalaryAmount { get; set; }
    public Guid OrganizationUnitId { get; set; }
    public decimal OtherAllowanceAmount { get; set; }
    public decimal OtWorkingDay { get; set; }
    public decimal OtWorkingSalaryAmount { get; set; }
    public decimal OtWorkingValue { get; set; }
    public decimal PitDeductionAmount { get; set; }
    public string PositionName { get; set; }
    public decimal SalaryAllowanceAmount { get; set; }
    public decimal SalaryCoefficient { get; set; }
    public decimal SocialInsuranceAmount { get; set; }
    public decimal SortOrder { get; set; }
    public decimal SumOfDeductionAmount { get; set; }
    public decimal TotalAmount { get; set; }
    public decimal UnemploymentInsurranceAmount { get; set; }
    public decimal WorkingDay { get; set; }
    public decimal WorkingDayUnitPrice { get; set; }
    public decimal WorkingHourUnitPrice { get; set; }
    public decimal WorkingSalaryAmount { get; set; }
    public decimal ColumnCoef1 { get; set; }
    public decimal ColumnCoef2 { get; set; }
    public decimal ColumnCoef3 { get; set; }
    public decimal ColumnCoef4 { get; set; }
    public decimal ColumnCoef5 { get; set; }
    public string EmployeeCode { get; set; }
    public string EmployeeName { get; set; }
    public string OrganizationUnitCode { get; set; }
    public string OrganizationUnitName { get; set; }
    public decimal AgreementSalary { get; set; }
    public decimal NumberOfDependent { get; set; }
    public Guid BranchId { get; set; }
    public Guid AccountObjectId { get; set; }
    public bool Inactive { get; set; }
    public decimal EmployeeContractType { get; set; }
    public decimal OverTimeDayNomal { get; set; }
    public decimal OverTimeDayWeekend { get; set; }
    public decimal OverTimeDayHoliday { get; set; }
    public decimal OverTimeNightNomal { get; set; }
    public decimal OverTimeNightWeekend { get; set; }
    public decimal OverTimeNightHoliday { get; set; }
    public decimal ProductQuantity { get; set; }
    public decimal ProductSalaryAmount { get; set; }
    public decimal BonusAmount { get; set; }
    public string MisaCodeId { get; set; }
    public DateTimeOffset CreatedDate { get; set; }
    public string CreatedBy { get; set; }
    public DateTimeOffset ModifiedDate { get; set; }
    public string ModifiedBy { get; set; }
    public bool AutoRefno { get; set; }
    public bool ForceUpdate { get; set; }
    public decimal EditVersion { get; set; }
    public decimal State { get; set; }
}
